### ISSUE TITLE
Only paragraph block?

### ISSUE THREAD

**Issue by pol76** [lubusIN/block-background#2]
Why not adding it to any block?

**Comment by ajitbohra** [comment]
@pol76 it works on any block

**Comment by pol76** [comment]
@ajitbohra , not according to my tests with latest Gutenberg version. See image attached. No background options for headings for example.

![capture](https://user-images.githubusercontent.com/25163253/39086146-0fb2fdb8-4553-11e8-9339-38567d162422.JPG)

**Comment by ajitbohra** [comment]
@pol76 thanks for reporting this yes it's not working with headings on the latest version, looking into.

**Comment by ajitbohra** [comment]
@pol76 latest release fixes this
