### ISSUE TITLE
Button display issue

### ISSUE THREAD

**Issue by ajitbohra** [lubusIN/block-background#20]
<img width="590" alt="bg-button-issue" src="https://user-images.githubusercontent.com/1039236/78648211-4e975b80-78d9-11ea-9428-a77930a358e7.png">

**Comment by NaveenKharwar** [comment]
Resolved: [https://github.com/lubusIN/block-background/pull/24#issue-400745434](https://github.com/lubusIN/block-background/pull/24#issue-400745434)
