### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cuisineandtravel** [lubusIN/block-background#4]
I uploaded the plugin but none of the options show up in the sidebar. Great idea though.

**Comment by ajitbohra** [comment]
@cuisineandtravel yes plugin compatibility with latest Gutenberg is pending we will soon release an update  for the same.

**Comment by cuisineandtravel** [comment]
Thank you!


[image: logo]
*Sondra Barker*
*Purveyor of Exceptional Eats and Escapes*
Sondra@cuisineandtravel.com |
http://www.CuisineandTravel.com
<http://facebook.com/cuisineandtravel> <http://instagram.com/sondrabarker>
<http://twitter.com/cuisinetravel> <http://instagram.com/cuisineandtravel>
Our Latest Article: The AltaMed Food and Wine Festival OC Meets Napa
<http://cuisineandtravel.com/2018/08/17/altamed-food-and-wine/>
Recent Photos:
<https://www.instagram.com/p/BmYgeCgA-LY/>
<https://www.instagram.com/p/BmJA64WAxfU/>
<https://www.instagram.com/p/BldTrWog2VS/>
<https://www.instagram.com/p/BlatqgPApgf/>
<https://www.instagram.com/p/BlTGZX6A5PA/>
<https://www.instagram.com/p/BkxpcFogWkb/>

**Comment by wheublein** [comment]
Plugin is still nonfunctional. If you don't have time to work on it, I can attempt to edit a fork for compatibility with latest Gutenberg. Do you have any suggestions on where the incompatibilities might be found?

**Comment by ajitbohra** [comment]
@wheublein updates will be up in a couple of days

**Comment by ajitbohra** [comment]
@cuisineandtravel  @wheublein plugin is now compatible with the latest version of Gutenberg
